spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/datn_4bee"
    username: root
    password: nguyenduykhanh

  mail:
    host: smtp.gmail.com
    port: 587
    username: khanhndph44928@fpt.edu.vn
    password: pgxokxbryejuvhkv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
